"""init schema

Revision ID: 1b219e79bbcf
Revises: 
Create Date: 2026-03-03 22:34:37.256459
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b219e79bbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('athlete', 'trainer', 'admin', name='user_role'), nullable=False),
    sa.Column('unit_pref', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_table('cardio_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('running', 'rowing', 'cycling', 'walking', 'other', name='cardio_type'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_sessions_athlete_id'), 'cardio_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_cardio_sessions_date'), 'cardio_sessions', ['date'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_scope', sa.Enum('global', 'trainer', 'athlete', name='owner_scope'), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('strength', 'cardio', name='exercise_type'), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('trainer_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trainer_id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'athlete_id', name='uq_trainer_athlete')
    )
    op.create_index(op.f('ix_trainer_assignments_athlete_id'), 'trainer_assignments', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_trainer_assignments_trainer_id'), 'trainer_assignments', ['trainer_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_owner_id'), 'workout_templates', ['owner_id'], unique=False)
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', name='scheduled_status'), nullable=False),
    sa.Column('source', sa.Enum('trainer', 'athlete', 'api', name='scheduled_source'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_workouts_athlete_id'), 'scheduled_workouts', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_date'), 'scheduled_workouts', ['date'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_template_id'), 'scheduled_workouts', ['template_id'], unique=False)
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.Integer(), nullable=False),
    sa.Column('planned_weight', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_template_exercises_exercise_id'), 'workout_template_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_template_exercises_template_id'), 'workout_template_exercises', ['template_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('scheduled_workout_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_athlete_id'), 'workout_sessions', ['athlete_id'], unique=False)
    op.create_table('logged_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('template_exercise_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_exercise_id'], ['workout_template_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logged_exercises_exercise_id'), 'logged_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_logged_exercises_session_id'), 'logged_exercises', ['session_id'], unique=False)
    op.create_table('logged_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('logged_exercise_id', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('planned_weight', sa.Float(), nullable=True),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('done', 'skipped', name='set_status'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['logged_exercise_id'], ['logged_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logged_sets_logged_exercise_id'), 'logged_sets', ['logged_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logged_sets_logged_exercise_id'), table_name='logged_sets')
    op.drop_table('logged_sets')
    op.drop_index(op.f('ix_logged_exercises_session_id'), table_name='logged_exercises')
    op.drop_index(op.f('ix_logged_exercises_exercise_id'), table_name='logged_exercises')
    op.drop_table('logged_exercises')
    op.drop_index(op.f('ix_workout_sessions_athlete_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_template_exercises_template_id'), table_name='workout_template_exercises')
    op.drop_index(op.f('ix_workout_template_exercises_exercise_id'), table_name='workout_template_exercises')
    op.drop_table('workout_template_exercises')
    op.drop_index(op.f('ix_scheduled_workouts_template_id'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_date'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_athlete_id'), table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    op.drop_index(op.f('ix_workout_templates_owner_id'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_trainer_assignments_trainer_id'), table_name='trainer_assignments')
    op.drop_index(op.f('ix_trainer_assignments_athlete_id'), table_name='trainer_assignments')
    op.drop_table('trainer_assignments')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_cardio_sessions_date'), table_name='cardio_sessions')
    op.drop_index(op.f('ix_cardio_sessions_athlete_id'), table_name='cardio_sessions')
    op.drop_table('cardio_sessions')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
